[package]
name = "nebula"
version = "0.1.0"
authors = ["nicohman <nicohman@demenses.net>"]
edition = "2018"

[dependencies]
gog = { git = "https://github.com/nicohman/gog-rs" }
structopt = "0.2.10"
serde = "1.0.70"
serde_derive = "1.0"
serde_json = "1.0"
human-panic = "1.0.1"
confy = "0.3.1"
