image: archlinux
packages:
  - cargo
  - rsync
secrets:
  -  dcfce43c-8472-4e5d-89f8-319e9ff7cb1c
  - 89991b16-705b-4276-9178-bfc81c7fdd28
environment:
  RUST_BACKTRACE: "1"
  deploy: nicohman@demenses.net
sources:
  - https://git.sr.ht/~nicohman/wyvern
tasks:
  - build_test: |
      cd wyvern
      cargo build
  - setup: |
      mkdir wyvern/target/debug/game_dir
      mkdir wyvern/target/debug/knights
  - test : |
      cd wyvern/target/debug
      ./wyvern down "Knights" --first
      ./wyvern install gog_knights_of_pen_and_paper_1_edition_2.0.0.1.sh knights/
      echo "test" > knights/game/knightspp_Data/data.kopp
      ./wyvern sync saves knights knights/game/knightspp_Data/data.kopp --db ./game_dir
      ./wyvern sync push knights ./game_dir
      rm knights/game/knightspp_Data/data.kopp
      ./wyvern sync pull knights ./game_dir
      cat knights/game/knightspp_Data/data.kopp
  - build_release: |
      cd wyvern
      cargo build --release
  - deploy: |
      cd wyvern/target/release
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -rP wyvern $deploy:/home/nicohman/ravenserver-rs/static/wyvern-nightly
triggers:
- {action: email, condition: failure, to: Nico Hickman <nicohman@demenses.net>}
